# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\William\Desktop\Glimpse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\William\Desktop\Glimpse

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\William\Desktop\Glimpse\CMakeFiles C:\Users\William\Desktop\Glimpse\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\William\Desktop\Glimpse\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glimpse

# Build rule for target.
glimpse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glimpse
.PHONY : glimpse

# fast build rule for target.
glimpse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/build
.PHONY : glimpse/fast

src/circle.obj: src/circle.cpp.obj
.PHONY : src/circle.obj

# target to build an object file
src/circle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/circle.cpp.obj
.PHONY : src/circle.cpp.obj

src/circle.i: src/circle.cpp.i
.PHONY : src/circle.i

# target to preprocess a source file
src/circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/circle.cpp.i
.PHONY : src/circle.cpp.i

src/circle.s: src/circle.cpp.s
.PHONY : src/circle.s

# target to generate assembly for a file
src/circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/circle.cpp.s
.PHONY : src/circle.cpp.s

src/game.obj: src/game.cpp.obj
.PHONY : src/game.obj

# target to build an object file
src/game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/game.cpp.obj
.PHONY : src/game.cpp.obj

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/line.obj: src/line.cpp.obj
.PHONY : src/line.obj

# target to build an object file
src/line.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/line.cpp.obj
.PHONY : src/line.cpp.obj

src/line.i: src/line.cpp.i
.PHONY : src/line.i

# target to preprocess a source file
src/line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/line.cpp.i
.PHONY : src/line.cpp.i

src/line.s: src/line.cpp.s
.PHONY : src/line.s

# target to generate assembly for a file
src/line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/line.cpp.s
.PHONY : src/line.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rect.obj: src/rect.cpp.obj
.PHONY : src/rect.obj

# target to build an object file
src/rect.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/rect.cpp.obj
.PHONY : src/rect.cpp.obj

src/rect.i: src/rect.cpp.i
.PHONY : src/rect.i

# target to preprocess a source file
src/rect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/rect.cpp.i
.PHONY : src/rect.cpp.i

src/rect.s: src/rect.cpp.s
.PHONY : src/rect.s

# target to generate assembly for a file
src/rect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/rect.cpp.s
.PHONY : src/rect.cpp.s

src/rigidbody.obj: src/rigidbody.cpp.obj
.PHONY : src/rigidbody.obj

# target to build an object file
src/rigidbody.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/rigidbody.cpp.obj
.PHONY : src/rigidbody.cpp.obj

src/rigidbody.i: src/rigidbody.cpp.i
.PHONY : src/rigidbody.i

# target to preprocess a source file
src/rigidbody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/rigidbody.cpp.i
.PHONY : src/rigidbody.cpp.i

src/rigidbody.s: src/rigidbody.cpp.s
.PHONY : src/rigidbody.s

# target to generate assembly for a file
src/rigidbody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/rigidbody.cpp.s
.PHONY : src/rigidbody.cpp.s

src/tension.obj: src/tension.cpp.obj
.PHONY : src/tension.obj

# target to build an object file
src/tension.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/tension.cpp.obj
.PHONY : src/tension.cpp.obj

src/tension.i: src/tension.cpp.i
.PHONY : src/tension.i

# target to preprocess a source file
src/tension.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/tension.cpp.i
.PHONY : src/tension.cpp.i

src/tension.s: src/tension.cpp.s
.PHONY : src/tension.s

# target to generate assembly for a file
src/tension.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/tension.cpp.s
.PHONY : src/tension.cpp.s

src/util.obj: src/util.cpp.obj
.PHONY : src/util.obj

# target to build an object file
src/util.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/util.cpp.obj
.PHONY : src/util.cpp.obj

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... glimpse
	@echo ... src/circle.obj
	@echo ... src/circle.i
	@echo ... src/circle.s
	@echo ... src/game.obj
	@echo ... src/game.i
	@echo ... src/game.s
	@echo ... src/line.obj
	@echo ... src/line.i
	@echo ... src/line.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/rect.obj
	@echo ... src/rect.i
	@echo ... src/rect.s
	@echo ... src/rigidbody.obj
	@echo ... src/rigidbody.i
	@echo ... src/rigidbody.s
	@echo ... src/tension.obj
	@echo ... src/tension.i
	@echo ... src/tension.s
	@echo ... src/util.obj
	@echo ... src/util.i
	@echo ... src/util.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

