# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\pixil\Desktop\GlimpseGithub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\pixil\Desktop\GlimpseGithub

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\pixil\Desktop\GlimpseGithub\CMakeFiles C:\Users\pixil\Desktop\GlimpseGithub\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\pixil\Desktop\GlimpseGithub\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glimpse

# Build rule for target.
glimpse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glimpse
.PHONY : glimpse

# fast build rule for target.
glimpse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/build
.PHONY : glimpse/fast

src/app.obj: src/app.cpp.obj
.PHONY : src/app.obj

# target to build an object file
src/app.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/app.cpp.obj
.PHONY : src/app.cpp.obj

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/coll.obj: src/coll.cpp.obj
.PHONY : src/coll.obj

# target to build an object file
src/coll.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/coll.cpp.obj
.PHONY : src/coll.cpp.obj

src/coll.i: src/coll.cpp.i
.PHONY : src/coll.i

# target to preprocess a source file
src/coll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/coll.cpp.i
.PHONY : src/coll.cpp.i

src/coll.s: src/coll.cpp.s
.PHONY : src/coll.s

# target to generate assembly for a file
src/coll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/coll.cpp.s
.PHONY : src/coll.cpp.s

src/color.obj: src/color.cpp.obj
.PHONY : src/color.obj

# target to build an object file
src/color.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/color.cpp.obj
.PHONY : src/color.cpp.obj

src/color.i: src/color.cpp.i
.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s
.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/comp.obj: src/comp.cpp.obj
.PHONY : src/comp.obj

# target to build an object file
src/comp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/comp.cpp.obj
.PHONY : src/comp.cpp.obj

src/comp.i: src/comp.cpp.i
.PHONY : src/comp.i

# target to preprocess a source file
src/comp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/comp.cpp.i
.PHONY : src/comp.cpp.i

src/comp.s: src/comp.cpp.s
.PHONY : src/comp.s

# target to generate assembly for a file
src/comp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/comp.cpp.s
.PHONY : src/comp.cpp.s

src/gobj.obj: src/gobj.cpp.obj
.PHONY : src/gobj.obj

# target to build an object file
src/gobj.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/gobj.cpp.obj
.PHONY : src/gobj.cpp.obj

src/gobj.i: src/gobj.cpp.i
.PHONY : src/gobj.i

# target to preprocess a source file
src/gobj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/gobj.cpp.i
.PHONY : src/gobj.cpp.i

src/gobj.s: src/gobj.cpp.s
.PHONY : src/gobj.s

# target to generate assembly for a file
src/gobj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/gobj.cpp.s
.PHONY : src/gobj.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/v2.obj: src/v2.cpp.obj
.PHONY : src/v2.obj

# target to build an object file
src/v2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/v2.cpp.obj
.PHONY : src/v2.cpp.obj

src/v2.i: src/v2.cpp.i
.PHONY : src/v2.i

# target to preprocess a source file
src/v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/v2.cpp.i
.PHONY : src/v2.cpp.i

src/v2.s: src/v2.cpp.s
.PHONY : src/v2.s

# target to generate assembly for a file
src/v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/v2.cpp.s
.PHONY : src/v2.cpp.s

src/visual.obj: src/visual.cpp.obj
.PHONY : src/visual.obj

# target to build an object file
src/visual.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/visual.cpp.obj
.PHONY : src/visual.cpp.obj

src/visual.i: src/visual.cpp.i
.PHONY : src/visual.i

# target to preprocess a source file
src/visual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/visual.cpp.i
.PHONY : src/visual.cpp.i

src/visual.s: src/visual.cpp.s
.PHONY : src/visual.s

# target to generate assembly for a file
src/visual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\glimpse.dir\build.make CMakeFiles/glimpse.dir/src/visual.cpp.s
.PHONY : src/visual.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... glimpse
	@echo ... src/app.obj
	@echo ... src/app.i
	@echo ... src/app.s
	@echo ... src/coll.obj
	@echo ... src/coll.i
	@echo ... src/coll.s
	@echo ... src/color.obj
	@echo ... src/color.i
	@echo ... src/color.s
	@echo ... src/comp.obj
	@echo ... src/comp.i
	@echo ... src/comp.s
	@echo ... src/gobj.obj
	@echo ... src/gobj.i
	@echo ... src/gobj.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/v2.obj
	@echo ... src/v2.i
	@echo ... src/v2.s
	@echo ... src/visual.obj
	@echo ... src/visual.i
	@echo ... src/visual.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

